Resources:
  HeadScaleLightsailContainerService:
    Type: 'AWS::Lightsail::Container'
    Properties:
      ServiceName: headscale-asd
      Power: nano
      Scale: 1
      ContainerServiceDeployment:
        Containers:
          - ContainerName: headscale
            Image: 'johncarvalho/asd-dev:headscale1.0'
            Ports:
              - Port: '80'
                Protocol: HTTP
        PublicEndpoint:
          ContainerName: headscale
          ContainerPort: 80
          HealthCheckConfig:
            HealthyThreshold: 2
            UnhealthyThreshold: 10
            TimeoutSeconds: 59
            IntervalSeconds: 60
            Path: /
            SuccessCodes: 200-499
